name: build osmosis docker images

on: pull_request

jobs:
  build-image:
    name: build osmosis image and test it
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: test image with real data
        run: make test
