name: build postgis docker images

on: pull_request

jobs:
  build-image:
    name: build osmosis images and push
    runs-on: ubuntu-latest

    steps:
      - name: set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: checkout
        uses: actions/checkout@v2

      - name: build image
        run: make build
